namespace: dev

resources:
- ../../base
- namespace.yaml

nameSuffix: -dev

replicas:
- count: 1
  name: login-service

images:
- name: mad855/login-service
  newName: mad855/login-service
  newTag: dev-0bf65fd
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
