resources:
- ../../base
- namespace.yaml

nameSuffix: -qa

replicas:
- count: 2
  name: login-service

images:
- name: mad855/login-service
  newName: mad855/login-service
  newTag: qa-0b6856f
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
