namespace: prod

resources:
- ../../base
- namespace.yaml
- hpa.yaml

nameSuffix: -prod

replicas:
- count: 3
  name: login-service

images:
- name: mad855/login-service
  newName: mad855/login-service
  newTag: prod-b18e375

patchesStrategicMerge:
- resource-limit-patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
